### ISSUE TITLE
ask: creat new branch: support/4.0.x

### ISSUE THREAD

**Issue by joshyu** [EligaServices/djangocms-content-expiry#71]
Hi @Aiky30  / @adam-murray  / @Bernardvdv , 

We want to add django 4.2 support to this addon, but we want it work with CMS 4.0.1.x version.
Can you please help to create branch **support/4.0.x ** based on **main** branch ?

Thanks.

**Comment by Aiky30** [comment]
Hi @joshyu,

None of us have admin access to this repository. I would advise forking it in the FIL github, or ask Divio to fork it for you. 

Kind regards,
Andrew

**Comment by joshyu** [comment]
@Aiky30 ,

Has this project stopped support by Eliga?  I can fork it, but I want to keep all the changes in the same repo if possible.

**Comment by Aiky30** [comment]
Hi Josh,

Sadly Eliga is no more, they are no longer an active UK Company, so this repository can only be forked I'm afraid. 

You can fork this here: https://github.com/FidelityInternational, someone in the business should have the ability to do this, I think you should probably apply within to do this too so that you have full control.

**Comment by joshyu** [comment]
feel sad that Eliga is gone. I will fork it to our organization and continue working on it.
Thanks, Andrew.
